[package]
name = "hedwig"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
chrono = "0.4.43"
cron = "0.15.0"
dirs = "6.0.0"
flexi_logger = { version = "0.31", features = ["trc", "compress"] }
http = "1.4.0"
image = "0.25.9"
mac-notification-sys = "0.6"
notify = "8.2.0"
reqwest = { version = "0.12", features = ["json", "rustls-tls", "http2"] }
roxmltree = "0.21.1"
serde = { version = "1.0", features = ["derive"] }
tao = "0.34.5"
tokio = { version = "1.49.0", features = ["full"] }
toml = "0.9.12"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["env-filter", "time", "local-time"] }
tray-icon = "0.21.3"

[package.metadata.bundle]
name = "Hedwig"
identifier = "io.github.jessun.hedwig"
icon = ["./src/assets/app_icon.icns"]
version = "0.1.0"
copyright = "Copyright © 2026 jessun"
category = "Productivity"
short_description = "A minimal Gmail watcher for macOS."
long_description = """
Hedwig watches your Gmail inbox and notifies you of new messages.
"""
osx_ui_element = true

# 👇 新增：Release 编译配置
[profile.release]
opt-level = "z"     # 优化代码体积 (比默认的 "3" 更激进地压缩体积)
lto = true          # 启用链接时优化 (Link Time Optimization)，移除死代码
codegen-units = 1   # 降低并行度以换取更好的优化效果
panic = "abort"     #由于是应用，Panic 时直接退出，不进行栈展开 (省去大量 unwind 代码)
strip = true        # 自动剥离符号表 (相当于运行了 strip 命令)
